[workspace]
members = [
    "blockchain-source",
    "core",
    "deps",
    "fraos",
    "indexed-log-map",
    "multiverse",
    "cardano-cli-tools/cip1852-first-address",
]

[workspace.metadata.release]
shared-version = false
tag = true
